server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:file:./data/dailydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    open-in-view: false
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

# 生产环境日志配置
logging:
  level:
    com.dailyapp: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/dailyapp/application.log
    max-size: 100MB
    max-history: 30

# JWT配置
jwt:
  secret: ${JWT_SECRET:YourVerySecureJWTSecretKeyForProductionEnvironmentThatShouldBeAtLeast256BitsLong}
  expiration: 604800

# CORS配置 - 生产环境
cors:
  allowed-origins: "http://kekedaka.xin,https://kekedaka.xin,http://kekedaka.xin:8080,https://kekedaka.xin:8080,http://8.148.20.194:8080,https://8.148.20.194:8080"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# 应用配置
app:
  name: DailyApp
  version: 1.0.0
  environment: production
