server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:file:./data/dailydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters
  expiration: 604800000 # 7 days in milliseconds (7 * 24 * 60 * 60 * 1000)

logging:
  level:
    org.springframework.security: DEBUG
    com.dailyapp: DEBUG
